---
title: "`r yaml::read_yaml('settings.yml')$view` Task View analysis"
logo: images/logo_white.svg
date: last-modified
format: 
  dashboard:
    orientation: columns
    nav-buttons: github
theme: 
  - cosmo
  - custom.scss
---

```{r}
knitr::opts_chunk$set(
  echo = FALSE
)
```

# Analysis

```{r}
tf <- tempfile(fileext = ".md")
download.file(
  paste0(
    "https://github.com/cran-task-views/",
    yaml::read_yaml("settings.yml")$view,
    "/raw/main/",
    yaml::read_yaml("settings.yml")$view,
    ".md"
  ),
  tf
)
```

```{r, message = FALSE}
library(ctv)
library(pkgsearch)
library(dplyr)
library(purrr)
library(ggplot2)
theme_set(
  theme_minimal(base_size = 18)
)
```

```{r}
ctv_pkgs <- ctv::read.ctv(tf) %>%
  purrr::pluck("packagelist", "name") 
```

```{r, cache = TRUE}
pkg_versions <- ctv_pkgs |> 
  purrr::map(pkgsearch::cran_package_history) |> 
  dplyr::bind_rows() |> 
  dplyr::mutate(
    date = lubridate::ymd_hms(date),
    maintainer = trimws(stringr::str_extract(Maintainer, "^[^<]+"))
  )
```

```{r}
ctv_pkg_descriptions <- pkg_versions |> 
  group_by(Package) |> 
  filter(date == max(date)) |> 
  ungroup()
```

```{r}
gh_repos <- read.csv("https://raw.githubusercontent.com/cran-task-views/Epidemiology/main/data/source_repositories.csv")
```

```{r}
authors <- pkg_versions |> 
  dplyr::transmute(
    Author = gsub("<U+000a>", " ", Author, fixed = TRUE),
    Author = gsub(" and ", ", ", Author, fixed = TRUE),
    Author = gsub("\\bwith contributions (of|from|by)\\b", ", ", Author),
    parsed_authors_r = purrr::map(`Authors@R`, ~ tryCatch(format(eval(parse(text = .x)), include = c("given", "family")), error = function(e) NA)),
    parsed_authors = strsplit(gsub("<[^>]*>", "", gsub("\\([^)]*\\)", "", gsub("\\[(\\w| |,)*\\]", "", Author))), "[[:space:]]*,+[[:space:]]*,*"),
    date = date,
    package = Package,
    maintainer = maintainer
  ) |> 
  dplyr::mutate(
    auts = coalesce(parsed_authors, parsed_authors_r),
    auts = map(auts, stringi::stri_trans_general, "ASCII"),
    auts = map(auts, stringr::str_replace_all, "[[:punct:]]", " "),
    auts = map(auts, stringr::str_replace_all, "[[:space:]]+", " "),
    auts = map(auts, stringr::str_replace_all, " \\w ", " "), # remove middle names
    auts = map(auts, stringr::str_remove_all, "et al"),
    auts = map(auts, trimws),
    maintainer = stringi::stri_trans_general(maintainer, "ASCII"),
    maintainer = stringr::str_remove_all(maintainer, "[[:punct:]]"),
    maintainer = trimws(maintainer),
    .keep = "unused"
  ) |> 
  select(-Author) |> 
  tidyr::unnest_longer(auts) |> 
  dplyr::mutate(auts = case_when(
    auts %in% c("Jose Lozano", "Lozano Jose E") ~ "Jose Lozano Alonso",
    auts == "K Seppa" ~ "Karri Seppa",
    auts == "Kevis Weiss" ~ "Kevin Weiss",
    auts == "Michael Fay User" ~ "Michael Fay",
    auts == "Rich FitzJohn" ~ "Rich Fitzjohn",
    auts == "Tomas Aragon Developer" ~ "Tomas Aragon",
    auts == "Carles Breto" ~ "Carles Martinez Breto",
    auts == "Isaac Fung" ~ "Isaac Chun Hai Fung",
    auts == "V Wimmer" ~ "Valentin Wimmer",
    auts == "T Correa" ~ "Thais Correa",
    auts == "S Meyer" ~ "Sebastian Meyer",
    auts == "M Salmon" ~ "Maelle Salmon",
    auts == "M Rantanen" ~ "Matti Rantanen",
    auts == "Ahmad family = Rabiee" ~ "Ahmad Rabiee",
    auts == "D Sabanes Bove" ~ "Daniel Sabanes Bove",
    auts == "Daniel Wollschlaeger User" ~ "Daniel Wollschlaeger",
    auts == "Eamon O Dea" ~ "Eamon Dea",
    auts == "Ed Ionides" ~ "Edward Ionides",
    auts == "J Miettinen" ~ "Joonas Miettinen",
    auts == "L Held" ~ "Leonhard Held",
    TRUE ~ auts
  )) |> 
  dplyr::mutate(
    switched = format(format(as.person(auts), c("family", "given"))),
    duplicated = switched %in% .data$auts
  )
```

## Dependencies and popularity {width=33%}

### Row {height=20%}

#### Col

```{r}
#| content: valuebox
#| title: "Number of packages"
list(
  color = "#10BED2",
  value = nrow(ctv_pkg_descriptions)
)
```

#### Col

```{r}
#| content: valuebox
#| title: "Package authors"
list(
  color = "#AEC800",
  value = n_distinct(authors$auts)
)
```

### Row {height=20%}

```{r github_stars, cache = TRUE}
stars <- gh_repos |> 
  na.omit() |> 
  dplyr::mutate(
    stars = purrr::map_int(github_repo, ~ length(gh::gh("/repos/{repo}/stargazers", repo = .x)))
  )
```

```{r}
#| content: valuebox
#| title: "GitHub stars"
list(
  color = "#EBE6E0",
  value = scales::label_number(big.mark = ",")(sum(stars$stars))
)
```

```{r cran-downloads, cache = TRUE}
ctv_pkgs_string <- glue::glue_collapse(ctv_pkgs, sep = ",")
yesterday <- Sys.Date() - 1

ctv_cran_stats <- "https://cranlogs.r-pkg.org/downloads/daily/2012-05-13:{yesterday}/{ctv_pkgs_string}" |> 
  glue::glue() |> 
  jsonlite::fromJSON() |> 
  dplyr::select(-start, -end) |> 
  tidyr::unnest(downloads)
```

```{r}
#| content: valuebox
#| title: "CRAN downloads"
list(
  color = "#DEFF00",
  value = scales::label_number(scale_cut = scales::cut_short_scale())(sum(ctv_cran_stats$downloads))
)
```

### Row

```{r}
pkg_versions |> 
  mutate(
    Soft = map_int(dependencies, ~ sum(.x$type == "Suggests")),
    Hard = map_int(dependencies, ~ n_distinct(.x$package[.x$type %in% c("Depends", "Imports", "LinkingTo")]))
  ) |> 
  tidyr::pivot_longer(
    cols = c(Soft, Hard),
    names_to = "Dependency type",
    values_to = "count"
  ) |>
  ggplot(aes(x = date, y = count, color = `Dependency type`, fill = `Dependency type`)) +
    geom_point() +
    geom_hline(yintercept = 20, linetype = "dashed", color = "#F04A4C") +
    annotate("text", x = as.POSIXct("2006-06-01"), y = 23, label = "Maximum number of hard dependencies for CRAN", hjust = 0.5, vjust = 1, color = "#F04A4C") +
    geom_smooth() +
    labs(
      title = "Number of hard and soft dependencies over time",
      x = "Date",
      y = "Number of dependencies"
    ) +
    theme(legend.position = "bottom") +
    scale_colour_manual(values = c(Soft = "#10BED2", Hard = "#AEC800"), guide = "none") +
    scale_fill_manual(values = c(Soft = "#10BED2", Hard = "#AEC800"))
```

## Best practices {width=33%}

```{r}
desc_checks <- ctv_pkg_descriptions %>%
  transmute(
    package            = Package,
    has_github_url     = startsWith(URL, "https://github.com/") | startsWith(BugReports, "https://github.com/"),
    uses_roxygen       = !is.na(RoxygenNote),
    has_knitr_vignette = grepl("knitr", VignetteBuilder),
    uses_testing       = purrr::map_lgl(dependencies, ~ any(.x$package %in% c("testthat", "testit", "unitizer", "RUnit", "tinytest"))),
    has_no_deprecated  = !purrr::map_lgl(dependencies, ~ any(.x$package %in% c("RUnit", "XML", "RCurl", "plyr", "reshape2"))),
    uses_authors_r     = !is.na(`Authors@R`),
    uses_orcid         = grepl("<https://orcid.org/", Author, fixed = TRUE)
  )
```

```{r load-gh-helpers}
library(httr)
source("_scripts/gh.R")
```

```{r gh-checks, cache = TRUE}
gh_checks <- gh_repos %>%
  transmute(
    package        = package,
    has_rmd_readme = purrr::map_lgl(github_repo, ~ gh_file_exists("README.Rmd", .x)),
    has_md_license = purrr::map_lgl(github_repo, ~ gh_file_exists("LICENSE.md", .x)),
    uses_pkgdown    = purrr::map_lgl(github_repo, ~ any(gh_file_list_exists(c("_pkgdown.yml", "_pkgdown.yaml", "pkgdown/pkgdown.yml"), .x))),
    uses_gha        = purrr::map_lgl(github_repo, ~ gh_file_exists(".github/workflows", .x)),
    has_news       = purrr::map_lgl(github_repo, ~ gh_file_exists("NEWS.md", .x)),
    has_contributing = purrr::map_lgl(github_repo, ~ any(gh_file_list_exists(c("CONTRIBUTING.md", ".github/CONTRIBUTING.md"), .x))),
    has_coc         = purrr::map_lgl(github_repo, ~ any(gh_file_list_exists(c("CODE_OF_CONDUCT.md", ".github/CODE_OF_CONDUCT.md"), .x)))
  )
```

```{r has-doi, cache = TRUE}
source("_scripts/has_doi.R")
extra_checks <- ctv_pkg_descriptions |> 
  transmute(
    has_doi = purrr::map_lgl(Package, has_doi),
    package = Package
  )
```

```{r}
all_checks <- merge(
  gh_checks,
  desc_checks,
  all = TRUE,
  by = "package"
) |> 
  merge(
    extra_checks,
    all = TRUE,
    by = "package"
  )
n_pkgs <- nrow(all_checks)
```

```{r}
check_descriptions <- tribble(
  ~check, ~description, ~details, ~category,
  "has_github_url", "Has a GitHub URL", "In `BugReports` or URL` fields in `DESCRIPTION`", "Metadata",
  "uses_roxygen", "Uses Roxygen", "As indicated by the presence of the `RoxygenNote` field in `DESCRIPTION`", "Documentation",
  "has_knitr_vignette", "Has a knitr vignette", "", "Documentation",
  "uses_testing", "Uses a testing framework", "As indicated by the presence of testthat, testit, unitizer, RUnit, tinytest in `Suggests`", "Testing & CI",
  "has_no_deprecated", "Does not depend on deprecated packages", "XML, RCurl, RUnit, plyr, or reshape2 packages", "Sustainability",
  "uses_authors_r", "Has Authors@R field", "", "Metadata",
  "uses_orcid", "Has ORCID in Author field", "", "Metadata",
  "has_rmd_readme", "Has README.Rmd", "", "Documentation",
  "has_md_license", "Has LICENSE.md", "", "Metadata",
  "uses_pkgdown", "Uses pkgdown", "", "Documentation",
  "uses_gha", "Uses GitHub Actions", "", "Testing & CI",
  "has_news", "Has NEWS.md", "", "Documentation",
  "has_contributing", "Has a contributing guide", "", "Community",
  "has_coc", "Has a code of conduct", "", "Community",
  "has_doi", "Provides a DOI for citation", "", "Metadata"
)
```

```{r}
all_checks |>
  tibble::column_to_rownames("package") |>
  t() |>
  as.data.frame() |>
  tibble::rownames_to_column("check") |>
  left_join(check_descriptions) |>
  select(-check) |> 
  mutate(
    passed = rowSums(pick(!c(description, details, category)), na.rm = TRUE) / n_pkgs * 100,
    .keep = "unused"
  ) |>
  arrange(desc(passed)) |> 
  gt::gt(groupname_col = "category", rowname_col = "description") |> 
  gt::cols_merge(
    columns = c(description, details),
    pattern = "{1}<br><small><i>{2}</i></small>"
  ) |> 
  gt::cols_width(passed ~ gt::px(100)) |> 
  gt::fmt_number(
    columns = passed,
    decimals = 0,
    pattern = "{x}%"
  ) |> 
  gt::data_color(
    method = "numeric",
    palette = "viridis",
    domain = c(0, 100)
  ) |> 
  gt::tab_stub_indent(
    rows = gt::everything(),
    indent = 5
  ) |> 
  gt::tab_header(
    title = gt::md("Adherence to good practices"),
    subtitle = gt::md("Good practices as defined by [rOpenSci dev guide](https://devguide.ropensci.org/index.html), and [Epiverse-TRACE blueprints](https://epiverse-trace.github.io/blueprints/).")
  ) |> 
  gt::tab_options(
    column_labels.hidden = TRUE,
    row_group.font.weight = "bold",
    table.font.size = "80%"
  )
```

## Authorship trends and sustainability {width=33%}

```{r}
maintainers_by_year <- pkg_versions |> 
  group_by(name = maintainer) |> 
  summarise(
    maintainer_since = lubridate::year(min(date))
  )

authors_by_year <- authors |>
  group_by(name = auts) |> 
  summarise(
    author_since = lubridate::year(min(date))
  )

full_join(maintainers_by_year, authors_by_year, by = "name") |>
  tidyr::pivot_longer(
    cols = c(maintainer_since, author_since),
    names_to = "role",
    values_to = "year"
  ) |> 
  dplyr::mutate(
    role = tools::toTitleCase(gsub("_since$", "", role))
  ) |> 
  ggplot(aes(x = year, fill = role)) +
    geom_histogram(binwidth = 1) +
    labs(
      title = "Recruitment of new authors & maintainers",
      x = "Date",
      y = "Number of new authors/maintainers",
      fill = ""
    ) +
    theme(legend.position = "bottom") +
    scale_fill_manual(values = c("Maintainer" = "#AEC800", "Author" = "#106BA0"))
```

```{r}
source("_scripts/parse_archive.R")

yearly_archivals <- archive_df |> 
  filter(package %in% ctv_pkgs) |> 
  dplyr::mutate(
    date = lubridate::ymd(archivals),
    year = lubridate::year(date),
    .keep = "unused"
  ) |> 
  count(year, name = "archivals") |> 
  dplyr::mutate(archivals = -archivals)
```

```{r}
pkg_versions |> 
  dplyr::mutate(
    first_release = Version == min(Version), 
    maintainer_change = maintainer != dplyr::lag(maintainer),
    .by = Package
  ) |>
  dplyr::group_by(year = lubridate::year(date)) |> 
  summarise(
    updates = sum(!first_release),
    `first releases` = sum(first_release),
    `maintainer transitions` = sum(maintainer_change),
    .groups = "drop"
  ) |> 
  dplyr::full_join(yearly_archivals, by = "year") |> 
  tidyr::pivot_longer(
    cols = c(updates, `first releases`, `maintainer transitions`, archivals),
    names_to = "release_type",
    values_to = "yearly_releases"
  ) |>
  ggplot(aes(x = year, y = yearly_releases, fill = release_type)) +
    geom_col() +
    labs(
      title = "New releases, updates and archivals",
      x = "Date", y = "Number of events",
      fill = ""
    ) +
    theme(legend.position = "bottom") +
    scale_fill_brewer(palette = "Set1")
```

# About
